apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: epl-scheduler
  name: epl-scheduler
  namespace: epl
  annotations:
    epl/staticinstance: cv22
spec:
  selector:
    matchLabels:
      app: epl-scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app: epl-scheduler
        name: epl-scheduler
      annotations:
        epl/staticinstance: cv22
    spec:
      serviceAccount: default
      containers:
        - name: epl-scheduler
          image: custom_scheduler:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: '0.1'
        - name: sidecar-proxy
          image: sidecar_proxy:latest
          imagePullPolicy: Never

