apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-go
  namespace: epl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-go
  template:
    metadata:
      labels:
        app: simple-go
    spec:
      schedulerName: epl-scheduler
      containers:
      - name: simple-go
        image: simple_go:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: simple-go-entrypoint
  namespace: epl
spec:
  type: NodePort
  selector:
    app: simple-go
  ports:
  - port: 6001
    targetPort: 6001
    nodePort: 30001

