---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ../kompose convert -f ion-docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: sfu
  name: sfu
spec:
  ports:
    - name: "50051"
      protocol: TCP
      port: 50051
    - name: "5000"
      port: 5000
      protocol: UDP
      targetPort: 5000
    - name: "5001"
      port: 5001
      protocol: UDP
      targetPort: 5001
    - name: "5002"
      port: 5002
      protocol: UDP
      targetPort: 5002
    - name: "5003"
      port: 5003
      protocol: UDP
      targetPort: 5003
    - name: "5004"
      port: 5004
      protocol: UDP
      targetPort: 5004
    - name: "5005"
      port: 5005
      protocol: UDP
      targetPort: 5005
    - name: "5006"
      port: 5006
      protocol: UDP
      targetPort: 5006
    - name: "5007"
      port: 5007
      protocol: UDP
      targetPort: 5007
    - name: "5008"
      port: 5008
      protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert -f ion-docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: sfu
  name: sfu
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sfu
  template:
    metadata:
      annotations:
        kompose.cmd: ../kompose convert -f ion-docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: sfu
    spec:
      containers:
        - image: pionwebrtc/ion-sfu:latest-grpc
          name: sfu
          ports:
            - containerPort: 50051
              protocol: TCP
            - containerPort: 5000
              protocol: UDP
            - containerPort: 5001
              protocol: UDP
            - containerPort: 5002
              protocol: UDP
            - containerPort: 5003
              protocol: UDP
            - containerPort: 5004
              protocol: UDP
            - containerPort: 5005
              protocol: UDP
            - containerPort: 5006
              protocol: UDP
            - containerPort: 5007
              protocol: UDP
            - containerPort: 5008
              protocol: UDP
            - containerPort: 5009
              protocol: UDP
            - containerPort: 5010
              protocol: UDP
            - containerPort: 5011
              protocol: UDP
            - containerPort: 5012
              protocol: UDP
            - containerPort: 5013
              protocol: UDP
            - containerPort: 5014
              protocol: UDP
            - containerPort: 5015
              protocol: UDP
            - containerPort: 5016
              protocol: UDP
            - containerPort: 5017
              protocol: UDP
            - containerPort: 5018
              protocol: UDP
            - containerPort: 5019
              protocol: UDP
            - containerPort: 5020
              protocol: UDP
