// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: net_helper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NetInfoRequest) Reset() {
	*x = NetInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_net_helper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetInfoRequest) ProtoMessage() {}

func (x *NetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_net_helper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetInfoRequest.ProtoReflect.Descriptor instead.
func (*NetInfoRequest) Descriptor() ([]byte, []int) {
	return file_net_helper_proto_rawDescGZIP(), []int{0}
}

type NetInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BwInfo []*BandwidthInfo  `protobuf:"bytes,1,rep,name=bwInfo,proto3" json:"bwInfo,omitempty"`
	TrInfo []*TracerouteInfo `protobuf:"bytes,2,rep,name=trInfo,proto3" json:"trInfo,omitempty"`
}

func (x *NetInfoReply) Reset() {
	*x = NetInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_net_helper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetInfoReply) ProtoMessage() {}

func (x *NetInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_net_helper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetInfoReply.ProtoReflect.Descriptor instead.
func (*NetInfoReply) Descriptor() ([]byte, []int) {
	return file_net_helper_proto_rawDescGZIP(), []int{1}
}

func (x *NetInfoReply) GetBwInfo() []*BandwidthInfo {
	if x != nil {
		return x.BwInfo
	}
	return nil
}

func (x *NetInfoReply) GetTrInfo() []*TracerouteInfo {
	if x != nil {
		return x.TrInfo
	}
	return nil
}

type BandwidthInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host      string  `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	SendBw    float32 `protobuf:"fixed32,2,opt,name=sendBw,proto3" json:"sendBw,omitempty"`
	ReceiveBw float32 `protobuf:"fixed32,3,opt,name=receiveBw,proto3" json:"receiveBw,omitempty"`
}

func (x *BandwidthInfo) Reset() {
	*x = BandwidthInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_net_helper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BandwidthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BandwidthInfo) ProtoMessage() {}

func (x *BandwidthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_net_helper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BandwidthInfo.ProtoReflect.Descriptor instead.
func (*BandwidthInfo) Descriptor() ([]byte, []int) {
	return file_net_helper_proto_rawDescGZIP(), []int{2}
}

func (x *BandwidthInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *BandwidthInfo) GetSendBw() float32 {
	if x != nil {
		return x.SendBw
	}
	return 0
}

func (x *BandwidthInfo) GetReceiveBw() float32 {
	if x != nil {
		return x.ReceiveBw
	}
	return 0
}

type TracerouteInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Hops []string `protobuf:"bytes,2,rep,name=hops,proto3" json:"hops,omitempty"`
}

func (x *TracerouteInfo) Reset() {
	*x = TracerouteInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_net_helper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TracerouteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracerouteInfo) ProtoMessage() {}

func (x *TracerouteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_net_helper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracerouteInfo.ProtoReflect.Descriptor instead.
func (*TracerouteInfo) Descriptor() ([]byte, []int) {
	return file_net_helper_proto_rawDescGZIP(), []int{3}
}

func (x *TracerouteInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TracerouteInfo) GetHops() []string {
	if x != nil {
		return x.Hops
	}
	return nil
}

var File_net_helper_proto protoreflect.FileDescriptor

var file_net_helper_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6e, 0x65, 0x74, 0x5f, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x6e, 0x22, 0x10, 0x0a, 0x0e, 0x4e, 0x65,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6d, 0x0a, 0x0c,
	0x4e, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2d, 0x0a, 0x06,
	0x62, 0x77, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6e,
	0x65, 0x74, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x06, 0x62, 0x77, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2e, 0x0a, 0x06, 0x74,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x65,
	0x74, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x06, 0x74, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x59, 0x0a, 0x0d, 0x42,
	0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x42, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x42, 0x77, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x42, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x42, 0x77, 0x22, 0x38, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x6f, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x70, 0x73,
	0x32, 0x4a, 0x0a, 0x0a, 0x4e, 0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x3c,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x2e, 0x6e,
	0x65, 0x74, 0x6d, 0x6f, 0x6e, 0x2e, 0x4e, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x6e, 0x2e, 0x4e, 0x65,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x39, 0x5a, 0x37,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x63, 0x68, 0x2e, 0x65, 0x64,
	0x75, 0x2f, 0x63, 0x73, 0x2d, 0x65, 0x70, 0x6c, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x2d, 0x62, 0x77,
	0x2d, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2f, 0x6e, 0x65, 0x74, 0x6d, 0x6f,
	0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_net_helper_proto_rawDescOnce sync.Once
	file_net_helper_proto_rawDescData = file_net_helper_proto_rawDesc
)

func file_net_helper_proto_rawDescGZIP() []byte {
	file_net_helper_proto_rawDescOnce.Do(func() {
		file_net_helper_proto_rawDescData = protoimpl.X.CompressGZIP(file_net_helper_proto_rawDescData)
	})
	return file_net_helper_proto_rawDescData
}

var file_net_helper_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_net_helper_proto_goTypes = []interface{}{
	(*NetInfoRequest)(nil), // 0: netmon.NetInfoRequest
	(*NetInfoReply)(nil),   // 1: netmon.NetInfoReply
	(*BandwidthInfo)(nil),  // 2: netmon.BandwidthInfo
	(*TracerouteInfo)(nil), // 3: netmon.TracerouteInfo
}
var file_net_helper_proto_depIdxs = []int32{
	2, // 0: netmon.NetInfoReply.bwInfo:type_name -> netmon.BandwidthInfo
	3, // 1: netmon.NetInfoReply.trInfo:type_name -> netmon.TracerouteInfo
	0, // 2: netmon.NetMonitor.GetNetInfo:input_type -> netmon.NetInfoRequest
	1, // 3: netmon.NetMonitor.GetNetInfo:output_type -> netmon.NetInfoReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_net_helper_proto_init() }
func file_net_helper_proto_init() {
	if File_net_helper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_net_helper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_net_helper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_net_helper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BandwidthInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_net_helper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TracerouteInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_net_helper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_net_helper_proto_goTypes,
		DependencyIndexes: file_net_helper_proto_depIdxs,
		MessageInfos:      file_net_helper_proto_msgTypes,
	}.Build()
	File_net_helper_proto = out.File
	file_net_helper_proto_rawDesc = nil
	file_net_helper_proto_goTypes = nil
	file_net_helper_proto_depIdxs = nil
}
